# Generated by Django 2.0.1 on 2018-01-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
