# Generated by Django 2.0.1 on 2018-01-24 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20180124_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 17, 17, 37, 245947, tzinfo=utc)),
        ),
    ]
