# Generated by Django 2.0.1 on 2018-01-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20180124_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messaging.Message')),
                ('title', models.CharField(max_length=200)),
            ],
            bases=('messaging.message',),
        ),
        migrations.AlterField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='messaging.Question'),
        ),
    ]
