# Generated by Django 2.0.1 on 2018-01-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_auto_20180128_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(default='no_author', max_length=100),
        ),
    ]
